apiVersion: v1
kind: Pod
metadata:
  name: placeholder-name  # 동적으로 설정
  labels:
    agent-type: placeholder-agent-type  # 동적으로 설정
spec:
  containers:
    - name: placeholder-container-name  # 동적으로 설정
      image: innoagent/pod:1.1
      imagePullPolicy: Always
      env:
        - name: MINIO_URL
          value: "minio-service.robot.svc.cluster.local:9000"
        - name: MINIO_ACCESS_KEY
          value: "minioadmin"
        - name: MINIO_SECRET_KEY
          value: "qwe1212qwe1212"
        - name: MINIO_BUCKET_NAME
          value: "rosbag-data"

